# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_links:
  enabled: true
  collections: true

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column Jekyll theme that pairs a prominent sidebar with uncomplicated content.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
